### ISSUE TITLE
pip install QuantumInformation commad is not working

### ISSUE THREAD

**Issue by viveksabale1998** [pranay1990/QuantumInformation#1]
pip install QuantumInformation 

i am unable to install it as its showing  error

error: subprocess-exited-with-error-:
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [10 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\lenovo\AppData\Local\Temp\pip-install-2hrv0rqw\quantuminformation_4ef0206c7a8f41319a5c6809279a02c3\setup.py", line 5, in <module>
      long_description = (this_directory / "QuantumInformation/README.md").read_text()
    File "C:\Users\lenovo\anaconda3\lib\pathlib.py", line 1134, in read_text
      with self.open(mode='r', encoding=encoding, errors=errors) as f:
    File "C:\Users\lenovo\anaconda3\lib\pathlib.py", line 1119, in open
      return self._accessor.open(self, mode, buffering, encoding, errors,
  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-install-2hrv0rqw\\quantuminformation_4ef0206c7a8f41319a5c6809279a02c3\\QuantumInformation\\README.md'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by pranay1990** [comment]
Hi @viveliitm, 
I am extremely sorry for replying so late. Thank you for reaching out and bringing the issue to my attention regarding the error messages you encountered while trying to download the code for my book "An Object-Oriented Python Cookbook." I apologize for any inconvenience this may have caused. I appreciate your patience, and I'm pleased to inform you that the bug has been identified and fixed. The issue stemmed from the incorrect location of the README.md file.
You should now be able to successfully download the code as per the instructions on page 28 of the book. Please try the following step:

> pip install QuantumInformation

I have also updated the GitHub code also. I sincerely apologize for any frustration this issue may have caused and appreciate your understanding. If you encounter any further issues or require additional assistance, please don't hesitate to reach out to us.
